# Generated by Django 5.0.6 on 2024-06-02 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotesEnvironment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=128)),
                ('admins', models.ManyToManyField(related_name='administrates', to='account.userprofile')),
                ('collaborator', models.ManyToManyField(related_name='collaborates', to='account.userprofile')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='NotesPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('hidden', models.BooleanField(default=False)),
                ('editable', models.BooleanField(default=False)),
                ('notesEnvironment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.notesenvironment')),
            ],
        ),
    ]
